version: "3.8"

services:
  proxy:
    build: Proxy
    restart: on-failure
    ports:
      - 5500:5500
  proxy-front:
    environment:
      FRONT_ROOT_ITLAB: http://127.0.0.1.xip.io:5500/front/front
      FRONT_ROOT_PROJECTS: http://127.0.0.1.xip.io:5500/front/projects/rtuitlab-projects.js
      FRONT_ROOT_PROJECTS_API_BASE: http://127.0.0.1.xip.io:5500
  front:
    environment:
      VUE_APP_REDIRECT_URI: http://127.0.0.1.xip.io:5500/logincallback
      VUE_APP_POST_LOGOUT_REDIRECT_URL: http://127.0.0.1.xip.io:5500
      VUE_APP_SILENT_REDIRECT_URI: http://127.0.0.1.xip.io:5500/silentcallback

  reports-front:
    environment:
      ConnectionStrings__ReportsApiBase: http://proxy:5500
      ConnectionStrings__UsersApiBase: http://proxy:5500
      ConnectionStrings__SalaryApiBase: http://proxy:5500
      ConnectionStrings__FilesApiBase: http://proxy:5500/api/mfs


