version: "3.8"

services:
    proxy:
        image: rtuitlab/itlab-proxy:${SERVICE_VERSION:-latest}
        ports:
            - 5500:5500
            - 5501:5501
        depends_on:
            - identity
            - back
            - front
            - docsgen
        restart: on-failure

    identity:
        image: rtuitlab/itlab-identity:${SERVICE_VERSION:-latest}
        depends_on:
            - postgres
        environment:
            - ASPNETCORE_ENVIRONMENT=${SERVICE_ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__ConfigurationDbConnection=${SERVICE_IDENTITY_DATABASE}
            - ConnectionStrings__PersistedGrantDbConnection=${SERVICE_IDENTITY_DATABASE}
            - ConnectionStrings__IdentityDbConnection=${SERVICE_POSTGRES_USERS_AND_EVENTS_DB}
            - AdminConfiguration__IdentityAdminBaseUrl=${SERVICE_IDENTITY_ADMIN_URL}
        networks:
            default:
                aliases:
                    - 127.0.0.1.xip.io
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    back:
        image: rtuitlab/itlab-back:${SERVICE_VERSION:-latest}
        environment:
            - ASPNETCORE_ENVIRONMENT=${SERVICE_ASPNETCORE_ENVIRONMENT}
            - UseDebugEmailSender=true
            - ConnectionStrings__POSTGRES=${SERVICE_POSTGRES_USERS_AND_EVENTS_DB}
        depends_on:
            - postgres
            - identity
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    front:
        image: rtuitlab/itlab-front:${SERVICE_VERSION:-latest}
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    identity-admin:
        image: rtuitlab/itlab-identity-admin:${SERVICE_VERSION:-latest}
        depends_on:
            - postgres
        environment:
            - ASPNETCORE_ENVIRONMENT=${SERVICE_ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__ConfigurationDbConnection=${SERVICE_IDENTITY_DATABASE}
            - ConnectionStrings__PersistedGrantDbConnection=${SERVICE_IDENTITY_DATABASE}
            - ConnectionStrings__IdentityDbConnection=${SERVICE_POSTGRES_USERS_AND_EVENTS_DB}
            - ConnectionStrings__AdminLogDbConnection=${SERVICE_IDENTITY_DATABASE}
            - ConnectionStrings__AdminAuditLogDbConnection=${SERVICE_IDENTITY_DATABASE}

            - AdminConfiguration__IdentityAdminRedirectUri=${SERVICE_IDENTITY_ADMIN_URL}/signin-oidc
            - AdminConfiguration__IdentityServerBaseUrl=${SERVICE_IDENTITY_URL}
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    docsgen:
        image: rtuitlab/itlab-docsgen:${SERVICE_VERSION:-latest}
        depends_on:
            - back
        volumes:
            - ./Configuration/docsgen.properties:/application.properties
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    projects-back:
        image: rtuitlab/itlab-projects-back:${SERVICE_VERSION:-latest}
        depends_on:
            - mongo
        volumes:
            - ./Configuration/projects-back.json:/app/config.json
            - ./Configuration/projects-back-auth.json:/app/auth_config.json
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    projects-front:
        image: rtuitlab/itlab-projects-front:${SERVICE_VERSION:-latest}
        depends_on:
            - projects-back
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=password
        # wsl2 issue
        # volumes:
        #     - itlab_postgres:/var/lib/postgresql/data
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    mongo:
        image: mongo
        volumes:
            - itlab_postgres:/data/db
        ports:
            - 27020:27017
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 5588:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@test.com
            - PGADMIN_DEFAULT_PASSWORD=password

volumes:
    itlab_postgres:
    itlab_mongo:
