version: "3.8"

services:
  identity:
    networks:
    - net
  salary:
    networks:
    - net
  back:
    networks:
    - net
  proxy-back:
    networks:
    - net
  reports-front:
    networks:
    - net
  proxy-front:
    networks:
    - net
  mfs:
    networks:
    - net
  projects-back:
    networks:
    - net
  proxy:
    networks:
    - net
  docsgen:
    networks:
    - net
  reports-back:
    networks:
    - net
  identity-admin:
    networks:
    - net
  front:
    networks:
    - net
  projects-front:
    networks:
    - net
networks:
  net:
    driver: overlay