version: "3.8"

services:
    proxy:
        build: Proxy
    identity:
        build: ITLab-Identity/src/ITLab.Identity.STS.Identity/deploy
        # ports:
            # - 5501:5501
    back:
        build: ITLab-Back/deploy
        ports:
            - 5502:5502
    front:
        build: ITLab-Front/deploy
        ports:
            - 5503:5503
    identity-admin:
        build: ITLab-Identity/src/ITLab.Identity.Admin/deploy
        ports:
            - 5504:5504
    docsgen:
        build: ITLab-DocsGen
        ports:
            - 5505:8080
    projects-back:
        build: ITLab-Projects/src/api
        ports:
            - 5506:5506
